version: '3'
services:
  api:
    container_name: wijnen-api
    ports:
      - "6969:5000"
    build:
      context: ./api
      dockerfile: Dockerfile

  database:
    image: mongo:latest
    ports:
      - "27017:27017"
    container_name: wijnen-db
    volumes:
      - ./mongo-volume:/data/db
